### ISSUE TITLE
AttributeError: 'module' object has no attribute 'run'

### ISSUE THREAD

**Issue by rykener** [Carreau/friendlyautopep8#3]
Am I using this wrong? Or do I need a different version of python to access `subprocess.run`?

OS: OSX 10.11
Python 3.4

```
(pep8) e (master) pep8 $ pip install friendlyautopep8
Collecting friendlyautopep8
  Using cached friendlyautopep8-0.0.1-py2.py3-none-any.whl
Installing collected packages: friendlyautopep8
Successfully installed friendlyautopep8-0.0.1

...

(pep8) e (master) pep8 $ friendlyautopep8
Traceback (most recent call last):
  File "/Users/echarney/.virtualenvs/pep8/bin/friendlyautopep8", line 11, in <module>
    sys.exit(run_on_cwd())
  File "/Users/echarney/.virtualenvs/pep8/lib/python3.4/site-packages/friendlyautopep8/__init__.py", line 37, in run_on_cwd
    for fname, linespairs in find_files_and_lines():
  File "/Users/echarney/.virtualenvs/pep8/lib/python3.4/site-packages/friendlyautopep8/__init__.py", line 15, in find_files_and_lines
    p = subprocess.run('git diff -U0'.split(' '), stdout=subprocess.PIPE)
AttributeError: 'module' object has no attribute 'run'
```

**Comment by Carreau** [comment]
> Or do I need a different version of python to access subprocess.run?

Ah.. `subprocess.run` is 3.5+ only, the package shoudl be [tagged as such](https://github.com/Carreau/friendlyautopep8/blob/master/flit.ini#L9).

You can see that pip installed 0.0.1 (which I forgot to tag as 3.5+) otherwise it would have installed 0.0.3.
But as 0.0.3 and 0.0.2 as 3.5+, pip did avoid thoses

I'll see if I can make a version that uses `subprocess.Popen`, that should 3.3+

I removed 0.0.1 from PyPI to avoid further issues.

**Comment by Carreau** [comment]
I just release 0.0.4 that should be python 3.4 compatible. If you do a `pip install friendlyautopep8 --upgrade` you should get the new version.

**Comment by rykener** [comment]
that worked! Thanks for the quick response

I grant you +2 internets

**Comment by Carreau** [comment]
> that worked!

Great !

> I grant you +2 internets

Thanks, Kudos  to you too, you are likely the second or third user of this !
