### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by rykener** [Carreau/friendlyautopep8#4]
Hey, one more issue I found, I get this traceback when there are no files that have changes in them. It does work fine when I introduce changes. 

```
(pep8) e (foo) pep8 $ pip install friendlyautopep8 --upgrade
Collecting friendlyautopep8
  Downloading friendlyautopep8-0.0.4-py3-none-any.whl
Requirement already up-to-date: autopep8 in /Users/echarney/.virtualenvs/pep8/lib/python3.4/site-packages (from friendlyautopep8)
Requirement already up-to-date: pep8>=1.5.7 in /Users/echarney/.virtualenvs/pep8/lib/python3.4/site-packages (from autopep8->friendlyautopep8)
Installing collected packages: friendlyautopep8
  Found existing installation: friendlyautopep8 0.0.1
    Uninstalling friendlyautopep8-0.0.1:
      Successfully uninstalled friendlyautopep8-0.0.1
Successfully installed friendlyautopep8-0.0.4

...

(pep8) e (foo1) pep8 $ friendlyautopep8
Traceback (most recent call last):
  File "/Users/echarney/.virtualenvs/pep8/bin/friendlyautopep8", line 11, in <module>
    sys.exit(main())
  File "/Users/echarney/.virtualenvs/pep8/lib/python3.4/site-packages/friendlyautopep8/__init__.py", line 59, in main
    run_on_cwd()
  File "/Users/echarney/.virtualenvs/pep8/lib/python3.4/site-packages/friendlyautopep8/__init__.py", line 65, in run_on_cwd
    if not fname.endswith('.py'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by Carreau** [comment]
Ha ! Yes I've seen this one as well, and forgot to fill the bug report. 
It's getting late here but I might have a look later, unless you send a PR in the meantime. 

Thanks !
